server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.71.233.238:3306/server?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 2836115038
  data:
    redis:
      port: 6379
      host: 124.71.233.238
      password: 2836115038
      database1: 1
      database2: 2
      jedis:
        pool:
          max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 8 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）
  #邮箱配置
  mail:
    host: smtp.qq.com
    username: 2836115038@qq.com
    password: uxfhcxmonidtdgge
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      from: 2836115038@qq.com
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory




mybatis:
  mapper-locations: classpath:/mapper/**.xml

